apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdi-pipeline-apps
  namespace: sdi-ros-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdi-pipeline-apps
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: conf-macvlan-eth1
      labels:
        app: sdi-pipeline-apps
        role: sdi-apps
    spec:
      containers:
      - image: jsseok/sdi-pipeline-apps:latest
        args: ["ros2", "run", "perception", "seg_yolov8s"]
        imagePullPolicy: Always
        tty: true
        name: sdi-pipeline-apps
      nodeSelector:
        kubernetes.io/hostname: jsseok-linux-dev
      restartPolicy: Always
