apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdi-pipeline-perception
  namespace: sdi-ros-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdi-pipeline-apps
  template:
    metadata:
      annotations:
        #k8s.v1.cni.cncf.io/networks: conf-macvlan-eth1
        #k8s.v1.cni.cncf.io/networks: conf-macvlan-eth0
        k8s.v1.cni.cncf.io/networks: conf-macvlan-wlan
      labels:
        app: sdi-pipeline-apps
        role: sdi-apps
    spec:
      containers:
        #- image: jsseok/sdi-pipeline-apps:latest
      - image: jsseok/sdi-pipeline-apps:update
        args: ["ros2", "run", "perception", "seg_yolov8s"]
        imagePullPolicy: Always
        tty: true
        name: sdi-pipeline-perception
        env:
        - name: ROS_DOMAIN_ID
          value: "7"
      nodeSelector:
        #kubernetes.io/hostname: jsseok-linux-dev
        #kubernetes.io/hostname: ubuntu
        kubernetes.io/hostname: nano
      restartPolicy: Always
